-- Adicionar todas as colunas do formulário na tabela clientes
ALTER TABLE public.clientes
ADD COLUMN IF NOT EXISTS razao_social text,
ADD COLUMN IF NOT EXISTS nome_fantasia text,
ADD COLUMN IF NOT EXISTS cnpj_cpf text,
ADD COLUMN IF NOT EXISTS site_url text,
ADD COLUMN IF NOT EXISTS responsavel_nome text,
ADD COLUMN IF NOT EXISTS responsavel_email text,
ADD COLUMN IF NOT EXISTS responsavel_whatsapp text,
ADD COLUMN IF NOT EXISTS responsavel_cargo text,
ADD COLUMN IF NOT EXISTS tem_gestor_marketing boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS gestor_marketing_nome text,
ADD COLUMN IF NOT EXISTS gestor_marketing_email text,
ADD COLUMN IF NOT EXISTS gestor_marketing_whatsapp text,
ADD COLUMN IF NOT EXISTS tem_gestor_comercial boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS gestor_comercial_nome text,
ADD COLUMN IF NOT EXISTS gestor_comercial_email text,
ADD COLUMN IF NOT EXISTS gestor_comercial_whatsapp text,
ADD COLUMN IF NOT EXISTS nichos text[],
ADD COLUMN IF NOT EXISTS segmentos text[],
ADD COLUMN IF NOT EXISTS cidades text[],
ADD COLUMN IF NOT EXISTS bairros_regioes text[],
ADD COLUMN IF NOT EXISTS estado text,
ADD COLUMN IF NOT EXISTS cidade_regiao text,
ADD COLUMN IF NOT EXISTS tem_corretor_funcionario boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS qtd_corretores integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS qtd_funcionarios integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS estrutura_setores jsonb DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS tem_sdr boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS qtd_sdr_total integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS budget_mensal numeric,
ADD COLUMN IF NOT EXISTS distribuicao_sugerida jsonb DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS crm_url text,
ADD COLUMN IF NOT EXISTS crm_utilizado text,
ADD COLUMN IF NOT EXISTS meta_bm_id text,
ADD COLUMN IF NOT EXISTS google_ads_cid text,
ADD COLUMN IF NOT EXISTS contato_preferido text,
ADD COLUMN IF NOT EXISTS horarios_contato text,
ADD COLUMN IF NOT EXISTS lgpd_consent boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS observacoes_adicionais text,
ADD COLUMN IF NOT EXISTS status text DEFAULT 'Pendente',
ADD COLUMN IF NOT EXISTS approved_by uuid REFERENCES auth.users(id),
ADD COLUMN IF NOT EXISTS approved_at timestamp with time zone,
ADD COLUMN IF NOT EXISTS rejection_reason text,
ADD COLUMN IF NOT EXISTS archived boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS pixel_analytics_configurado boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS campanhas_ativas boolean DEFAULT false;

-- Adicionar índice para melhorar performance
CREATE INDEX IF NOT EXISTS idx_clientes_status ON public.clientes(status);
CREATE INDEX IF NOT EXISTS idx_clientes_email ON public.clientes(email);