// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgiadncyehpahtursqdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1naWFkbmN5ZWhwYWh0dXJzcWRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NzA2NTIsImV4cCI6MjA3MzM0NjY1Mn0.EWbFNG1guhXdoL2Ven3q4KF1SkaTqi-mO1j_9xOtr9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});